name: Print Variable or Secret

#on:
#  workflow_dispatch:
#    inputs:
#      environment:
#        description: 'Select environment (test or prod)'
#        required: true
#        default: 'test'
on:
 workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        type: environment

jobs:
  print-variable-or-secret:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set environment variable
      run: echo "ENVIRONMENT=${{ github.event.inputs.environment }}" >> $GITHUB_ENV

    - name: Print variable or secret
      run: |
        if [ "${{ env.ENVIRONMENT }}" == "Test" ]; then
          echo "Printing test variable"
          echo "TestVariable (secret): ${{ secrets.TESTSECRET }}"
          echo "TestVariable: ${{ vars.TEST_VARIABLE }}"
        elif [ "${{ env.ENVIRONMENT }}" == "Prod" ]; then
          echo "Printing prod secret"
          echo "ProdSecret: ${{ secrets.TESTSECRET }}"
          echo "ProdVariable: ${{ vars.TEST_VARIABLE }}"
        else
          echo "Invalid environment selected"
          exit 1
        fi
  
  print-variables-and-secrets:
    runs-on: windows-2022

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: print variables
      run: Write-Host "${{ env.TEST_VARIABLE }}"
